name: S3Deploy

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: S3 Sync
        run: |
          echo "Configuring AWS CLI"
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #unzip awscliv2.zip
          #sudo ./aws/install
          aws --version
          #aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          #aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          pip install -u boto3
          aws s3 rm s3://test875356/$GITHUB_REPOSITORY --recursive
          aws s3 sync ./ s3://test875356/$GITHUB_REPOSITORY --exclude ".git*" --exclude "*.md*"
        #with:
          #args: --acl bucket-owner-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude 'README.md'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          #AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          #SOURCE_DIR: './'
