name: S3Deploy

on:
  workflow_call:
     secrets:
       AWS_ACCESS_KEY_ID:
         required: true
       AWS_SECRET_ACCESS_KEY:
         required: true

jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: S3 Sync
        run: |
          aws --version
          aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}} 
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws configure set default.region eu-central-1
          aws s3 rm s3://test875356/${{github.event.repository.name}} --recursive --debug 
          aws s3 sync ./ s3://test875356/${{github.event.repository.name}} --exclude ".git*" --exclude "*.md*"
      
