name: S3Deploy

on:
  push:
    branches:
      - dev
      - main
  workflow_call:
  

jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      #- name: "Checkout"
        #uses: actions/checkout@v2
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::553352188627:role/Github-Test-Role
          aws-region: eu-central-1
      - name: S3 Sync
        run: |
          aws --version
          aws s3 rm s3://test875356/${{github.event.repository.name}} --recursive
          aws s3 sync ./ s3://test875356/${{github.event.repository.name}} --exclude ".git*" --exclude "*.md*"
      
